module.exports = async function ({ github, context, core, env }) {
    const [owner, repo] = process.env.FORK_REPO.split('/');
    const trackingIssueUrl = context.payload.issue.html_url;

    const body14 = [
        '',
        '### Task: Use GitHub Projects, Labels, and Assignments',
        '',
        '**Why this matters:**',
        'As projects grow, tracking issues and PRs can become overwhelming. GitHub Projects provides a visual board to organize work, while labels and assignments clarify what needs to be done and who is responsible. Together, these tools make collaboration more transparent and efficient.',
        '',
        '**Learning Goals:**',
        '- Create and use a GitHub Project board',
        '- Apply labels to categorize issues',
        '- Assign issues to team members',
        '',
        '### Detailed Steps:',
        '',
        '**Step 1: Create a GitHub Project**',
        '1. Go to your fork repository',
        '2. Click on the **"Projects"** tab',
        '3. Click **"New project"** (green button)',
        '4. Choose **"Board"** template (Kanban-style)',
        '5. Name it: `Preregistration Improvements`',
        '6. Click **"Create project"**',
        '',
        '**Step 2: Add existing issues to your project**',
        '1. In your project board, you\'ll see columns like "Todo", "In Progress", "Done"',
        '2. Click **"+ Add item"** at the bottom of the "Todo" column',
        '3. Search for and add the issues created in Milestone 10:',
        '   - Decide on meta-comment',
        '   - Update number of participants',
        '   - Correct materials\' description',
        '   - Clarify procedure',
        '   - Improve data analysis plan',
        '',
        '**Step 3: Use labels to categorize issues**',
        '1. Go to the **Issues** tab in your repository',
        '2. Click on one of your issues',
        '3. On the right sidebar, find **"Labels"**',
        '4. Click **"Labels"** and select or create appropriate labels:',
        '   - `documentation` - for writing/editing tasks',
        '   - `enhancement` - for improvements to existing content',
        '   - `question` - for items needing discussion',
        '   - Or create your own custom labels!',
        '5. **Important:** Add labels to at least one issue (required for completion)',
        '',
        '**Step 4: Assign issues to team members**',
        '1. While viewing an issue, look for **"Assignees"** on the right sidebar',
        '2. Click **"Assignees"** and select yourself or your partner',
        '3. This shows who is responsible for each task',
        '4. **Important:** Assign at least one issue (required for completion)',
        '5. Try assigning different issues to different team members to divide work',
        '',
        '**Step 5: Organize your workflow in the project board**',
        '1. **Drag an issue** from "Todo" to "In Progress" when you start working on it',
        '2. Notice how labels and assignees are visible on the project cards',
        '3. **Move to "Done"** when the issue is closed',
        '4. Use the project board to get a quick visual overview of progress',
        '',
        '**Step 6: Try advanced features (optional)**',
        '1. **Filter by label**: In the Issues tab, click on a label to see all issues with that label',
        '2. **Filter by assignee**: Use the assignee filter to see what\'s on your plate',
        '3. **Group by**: In your project, try grouping items by assignee or label',
        '4. **Add custom fields**: Click ⚙️ (settings) → Add field for priority or effort estimates',
        '',
        '**Expected results:**',
        '- ✓ A project board with your issues organized visually',
        '- ✓ At least one issue with a label',
        '- ✓ At least one issue with an assignee',
        '- ✓ Better overview of who is working on what',
        '- ✓ Clear categorization and status of all tasks',
        '',
        '**Discussion:** How might labels and assignments help prevent duplicate work? When might too many labels become confusing?',
        '',
        '**Pro tip:** You can link PRs to issues automatically by mentioning the issue number in PR descriptions (e.g., "Fixes #5")!',
        '',
        `**When done:** Comment \`/done 14\` [in the tracking issue](${trackingIssueUrl}).`,
        '',
        '**Note:** Our automated check will verify:',
        '1. You have created at least one project',
        '2. At least one issue has a label',
        '3. At least one issue has an assignee',
        '',
    ];

    await github.rest.issues.create({
        owner: owner,
        repo: repo,
        title: '[optional] Milestone 14: Use GitHub Projects, Labels, and Assignments - 🟡 Medium',
        body: body14.join('\n'),
        labels: ['enhancement']
    });
}
