module.exports = async function ({ github, context, core, env }) {
    const [owner, repo] = process.env.FORK_REPO.split('/');
    const trackingIssueUrl = context.payload.issue.html_url;

    const body15 = [
        '',
        '### Task: Learn Git Branching Interactively',
        '',
        '**Why this matters:**',
        'While GitHub\'s web interface is great for many tasks, understanding Git\'s underlying concepts—especially branching, merging, and rebasing—is crucial for handling complex scenarios, resolving conflicts, and collaborating effectively on larger projects. This interactive tutorial makes learning Git fun and visual!',
        '',
        '**What you\'ll learn:**',
        '- How Git commits form a tree structure',
        '- Creating and switching between branches',
        '- Merging branches and handling divergent histories',
        '- Rebasing to create linear histories',
        '- Working with remote repositories (push, pull, fetch)',
        '- Advanced techniques like cherry-pick, interactive rebase, and more',
        '',
        '**Time commitment:** 1+ hours (depending on difficulty level)',
        '',
        '### Detailed Steps:',
        '',
        '**Step 1: Go to the interactive tutorial**',
        '1. Open your browser and navigate to: **https://learngitbranching.js.org/**',
        '2. You\'ll see a visual Git sandbox with a command line interface',
        '3. The tutorial is completely interactive—you type real Git commands and see visual results!',
        '',
        '**Step 2: Choose your difficulty level**',
        '',
        '**🟢 Easy Level:**',
        'Complete the **"Introduction Sequence"** (Main tab):',
        '1. Introduction to Git Commits',
        '2. Branching in Git',
        '3. Merging in Git',
        '4. Rebase Introduction',
        '',
        'This takes about **20-30 minutes** and covers the fundamentals you need for basic Git workflows.',
        '',
        '**🟡 Medium Level:**',
        'Complete **"Introduction Sequence"** + **"Ramping Up"** (Main tab):',
        '1. All exercises from Easy level',
        '2. Detach yo\' HEAD',
        '3. Relative Refs (^)',
        '4. Relative Refs #2 (~)',
        '5. Reversing Changes in Git',
        '',
        'This takes about **45-60 minutes** and teaches you how to navigate Git history and undo changes.',
        '',
        '**🔴 Hard Level:**',
        'Complete **"Introduction Sequence"** + **"Ramping Up"** + **"Moving Work Around"** (Main tab):',
        '1. All exercises from Medium level',
        '2. Cherry-pick Intro',
        '3. Interactive Rebase Intro',
        '',
        'Then explore the **"Remote"** tab for distributed Git workflows!',
        '',
        'This takes **1-2+ hours** and gives you mastery over advanced Git techniques.',
        '',
        '**Step 3: Work through the exercises**',
        '1. Read each level\'s instructions carefully',
        '2. Type Git commands in the terminal at the bottom',
        '3. Watch the visual representation update in real-time',
        '4. If you get stuck, click **"Show Solution"** to see the answer',
        '5. Try to understand *why* each command works, not just copy the solution',
        '',
        '**Step 4: Try it in your repository (optional)**',
        '1. Open a terminal in your fork repository',
        '2. Try creating a branch: `git checkout -b test-branch`',
        '3. Make a commit and switch back: `git checkout main`',
        '4. Visualize your branches: `git log --oneline --graph --all`',
        '5. Delete your test branch: `git branch -d test-branch`',
        '',
        '**Expected results:**',
        '- ✓ Completed your chosen difficulty level of Learn Git Branching',
        '- ✓ Visual understanding of how Git stores history as a graph',
        '- ✓ Confidence to use branches, merge, and rebase',
        '- ✓ Ability to navigate and modify Git history',
        '',
        '**Discussion:** When would you use merge vs rebase? How might understanding Git branching help with collaborative research projects?',
        '',
        '**Pro tip:** You can always come back to https://learngitbranching.js.org/ later to practice more advanced levels!',
        '',
        `**When done:** Comment \`/done 15\` [in the tracking issue](${trackingIssueUrl}) and let us know which difficulty level you completed!`,
        '',
        '**Note:** This milestone is self-directed. We trust you to complete the exercises and learn at your own pace. The time investment is worth it—Git knowledge compounds over your entire career!',
        '',
    ];

    await github.rest.issues.create({
        owner: owner,
        repo: repo,
        title: '[optional] Milestone 15: Learn Git Branching Interactively - 🟢 Easy / 🟡 Medium / 🔴 Hard',
        body: body15.join('\n'),
        labels: ['enhancement']
    });
}
