module.exports = async function ({ github, context, core, env }) {
    const [owner, repo] = process.env.FORK_REPO.split('/');
    const trackingIssueUrl = context.payload.issue.html_url;

    const body19 = [
        '',
        '### Task: Create Releases and Tags for Research Milestones (🟡 Medium)',
        '',
        '**Why this matters:**',
        'Research projects have important milestones: submitting a preregistration, posting a preprint, submitting to a journal, presenting at a conference, or publishing the final paper. Git tags and GitHub releases let you create permanent snapshots of your project at these exact moments. This ensures reproducibility, provides citable versions, and creates an audit trail of your research evolution.',
        '',
        '**Real-world research milestones to tag:**',
        '- 📋 **Preregistration** - Before data collection begins',
        '- 📄 **Preprint submission** - Version uploaded to arXiv/bioRxiv/PsyArXiv',
        '- 📬 **Journal submission** - Exact version submitted to journal',
        '- 🔄 **Revision** - Version after addressing reviewer comments',
        '- ✅ **Acceptance** - Final accepted manuscript',
        '- 📚 **Publication** - Published version (may differ slightly from accepted)',
        '- 🎤 **Conference talks** - Version presented at specific events',
        '- 🏆 **Award/Recognition** - Version that received recognition',
        '',
        '**Learning Goals:**',
        '- Create Git tags for project milestones',
        '- Create GitHub releases with descriptions and assets',
        '- Understand semantic versioning for research',
        '- Set up Zenodo integration for long-term archival and DOIs',
        '',
        '### Detailed Steps:',
        '',
        '**Step 1: Understand tags vs releases**',
        '',
        '- **Tag**: A Git reference to a specific commit (like a bookmark)',
        '  - Lightweight: just a name pointing to a commit',
        '  - Annotated: includes message, date, author',
        '',
        '- **Release**: GitHub feature built on tags',
        '  - Includes release notes',
        '  - Can attach files (PDFs, datasets, etc.)',
        '  - Creates a permanent archive (.zip and .tar.gz)',
        '  - More discoverable and user-friendly',
        '',
        '**Step 2: Create your first tag (Command Line)**',
        '',
        'If using Codespaces or local Git:',
        '',
        '```bash',
        '# Make sure you\'re on the commit you want to tag',
        'git log --oneline -5',
        '',
        '# Create an annotated tag (recommended)',
        'git tag -a v1.0-preregistration -m "Version submitted for preregistration"',
        '',
        '# Or tag a specific commit',
        'git tag -a v1.0-preregistration abc123 -m "Preregistration version"',
        '',
        '# Push the tag to GitHub',
        'git push origin v1.0-preregistration',
        '',
        '# Or push all tags',
        'git push origin --tags',
        '```',
        '',
        '**Tag naming conventions for research:**',
        '```',
        'v1.0-preregistration',
        'v1.1-preprint',
        'v1.2-submission',
        'v1.3-revision1',
        'v1.4-revision2',
        'v2.0-acceptance',
        'v2.1-publication',
        'talk-cogsci2024',
        'talk-aps2025',
        '```',
        '',
        '**Step 3: Create a GitHub Release (Easy - Web Interface)**',
        '',
        '1. Go to your repository on GitHub',
        '2. Click **"Releases"** in the right sidebar (or `/releases` in URL)',
        '3. Click **"Draft a new release"** or **"Create a new release"**',
        '',
        '4. **Choose a tag:**',
        '   - Click "Choose a tag"',
        '   - Type: `v1.0-preregistration`',
        '   - Click "Create new tag: v1.0-preregistration on publish"',
        '',
        '5. **Target:** Make sure it points to `main` (or specific commit/branch)',
        '',
        '6. **Release title:** `Preregistration Submission - January 2025`',
        '',
        '7. **Description:** Write comprehensive release notes:',
        '```markdown',
        '## Preregistration Submission',
        '',
        'This release captures the exact version of our preregistration submitted to [OSF/AsPredicted] on January 15, 2025.',
        '',
        '### Study Details',
        '- **Research Question:** [Your question]',
        '- **Sample Size:** N = [number] participants',
        '- **Preregistration URL:** [Link to OSF/AsPredicted]',
        '',
        '### Contents',
        '- Complete preregistration document',
        '- Materials used for data collection',
        '- Planned analysis scripts',
        '',
        '### Changes Since Last Version',
        '- Clarified exclusion criteria',
        '- Added power analysis',
        '- Specified primary outcome measure',
        '',
        '### Citation',
        'If citing this version, please use: [Author] (2025). [Project name] - Preregistration. Retrieved from https://github.com/[username]/[repo]/releases/tag/v1.0-preregistration',
        '```',
        '',
        '8. **Attach files (optional but recommended):**',
        '   - Click "Attach binaries by dropping them here"',
        '   - Add: preregistration PDF, data collection scripts, etc.',
        '',
        '9. **Options:**',
        '   - ☐ Set as a pre-release (for drafts/testing)',
        '   - ☐ Set as the latest release',
        '',
        '10. Click **"Publish release"**',
        '',
        '**Step 4: Create releases for other milestones**',
        '',
        'Practice creating releases for these scenarios:',
        '',
        '**Preprint submission:**',
        '```',
        'Tag: v1.1-preprint-psyarxiv',
        'Title: Preprint Submission - PsyArXiv',
        'Description: Version uploaded to PsyArXiv on [date]',
        'Attach: manuscript PDF, supplementary materials',
        '```',
        '',
        '**Journal submission:**',
        '```',
        'Tag: v1.2-submission-psychsci',
        'Title: Journal Submission - Psychological Science',
        'Description: Version submitted to Psychological Science on [date]',
        'Attach: manuscript, figures, supplementary materials, cover letter',
        '```',
        '',
        '**Revision after review:**',
        '```',
        'Tag: v1.3-revision1',
        'Title: Revision 1 - Response to Reviewers',
        'Description: First revision addressing reviewer comments',
        'Attach: revised manuscript, response to reviewers, tracked changes',
        '```',
        '',
        '**Conference presentation:**',
        '```',
        'Tag: talk-cogsci2024',
        'Title: Talk at CogSci 2024 - Rotterdam',
        'Description: Version presented at Cognitive Science Society 2024',
        'Attach: slides PDF, poster, talk notes',
        '```',
        '',
        '**Final publication:**',
        '```',
        'Tag: v2.0-publication',
        'Title: Published Version - Psychological Science',
        'Description: Final published version (April 2025)',
        'Note: Link to official DOI',
        '```',
        '',
        '**Step 5: Set up Zenodo integration for long-term archival**',
        '',
        '**Why Zenodo?**',
        '- 🎯 Assigns DOIs (Digital Object Identifiers) to your releases',
        '- 📚 Long-term preservation (CERN infrastructure)',
        '- 📊 Makes your code/data citable',
        '- 🔒 Permanent archive even if GitHub disappears',
        '- 🆓 Free for open research',
        '',
        '**Setup Zenodo (one-time):**',
        '',
        '1. Go to **https://zenodo.org/** (or https://sandbox.zenodo.org/ for testing)',
        '2. Click **"Log in"** and choose **"Log in with GitHub"**',
        '3. Authorize Zenodo to access your GitHub account',
        '',
        '4. After login:',
        '   - Click your name (top right) → **"GitHub"**',
        '   - Or go directly to: https://zenodo.org/account/settings/github/',
        '',
        '5. **Enable your repository:**',
        '   - Find your repository in the list',
        '   - Click the **"ON"** toggle switch',
        '   - Zenodo will now watch for new releases',
        '',
        '6. **Create a release on GitHub** (as described above)',
        '',
        '7. **Zenodo automatically archives it:**',
        '   - Wait a few minutes',
        '   - Go back to Zenodo → GitHub page',
        '   - Click on your repository',
        '   - You\'ll see your release with a **DOI badge**!',
        '',
        '**Add Zenodo DOI badge to your README:**',
        '',
        '1. On Zenodo, click on your archived release',
        '2. Look for the **DOI badge** section',
        '3. Copy the Markdown code:',
        '```markdown',
        '[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1234567.svg)](https://doi.org/10.5281/zenodo.1234567)',
        '```',
        '4. Add it to your repository\'s README.md',
        '',
        '**Step 6: Best practices for research releases**',
        '',
        '✅ **DO:**',
        '- Create releases for all major research milestones',
        '- Write detailed release notes',
        '- Include context: what, when, where, why',
        '- Attach important files (PDFs, datasets)',
        '- Use consistent naming conventions',
        '- Link to external resources (OSF, journal articles)',
        '- Update your README with release badges',
        '',
        '❌ **DON\'T:**',
        '- Create releases for trivial changes',
        '- Use vague descriptions ("updated stuff")',
        '- Forget to push tags before creating releases',
        '- Delete or modify releases after publication (breaks citations)',
        '',
        '**Expected results:**',
        '- ✓ Created at least one release with detailed notes',
        '- ✓ Understand when to create releases in research workflows',
        '- ✓ (Optional) Set up Zenodo integration',
        '- ✓ (Optional) Added DOI badge to README',
        '',
        '---',
        '',
        '**Semantic versioning for research projects:**',
        '',
        'Adapted from software versioning for research:',
        '',
        '```',
        'v[MAJOR].[MINOR]-[MILESTONE]',
        '',
        'MAJOR: Significant research milestone (1 = preregistration, 2 = publication)',
        'MINOR: Iterations within that milestone (0, 1, 2...)',
        'MILESTONE: Descriptive label (preregistration, preprint, submission, etc.)',
        '```',
        '',
        'Examples:',
        '- `v1.0-preregistration` - First preregistration',
        '- `v1.1-preprint` - Preprint based on that preregistration',
        '- `v1.2-submission` - Journal submission',
        '- `v1.3-revision1` - First revision',
        '- `v2.0-publication` - Published version',
        '- `v2.1-erratum` - Correction/erratum',
        '',
        '**Discussion Questions:**',
        '- How might releases improve reproducibility in your field?',
        '- What information should be included in release notes for research?',
        '- How do DOIs from Zenodo help with academic citations?',
        '',
        '**Pro tips:**',
        '- 💡 Create releases *before* submitting/posting to capture the exact version',
        '- 💡 Link releases in your manuscripts: "Code available at [GitHub URL]/releases/tag/v1.2-submission"',
        '- 💡 Use Zenodo\'s concept DOI (always points to latest) vs version DOI (specific version)',
        '- 💡 For sensitive data, release only code/analysis scripts, not raw data',
        '- 💡 Consider creating releases for conference deadlines even before acceptance',
        '',
        `**When done:** Comment \`/done 19\` [in the tracking issue](${trackingIssueUrl}).`,
        '',
        '**Further reading:**',
        '- Zenodo-GitHub integration: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content',
        '- Making your code citable: https://guides.github.com/activities/citable-code/',
        '- OSF + GitHub integration: https://help.osf.io/article/211-connect-github-to-a-project',
        '',
    ];

    await github.rest.issues.create({
        owner: owner,
        repo: repo,
        title: '[optional] Milestone 19: Create Releases and Tags for Research Milestones - 🟡 Medium',
        body: body19.join('\n'),
        labels: ['enhancement']
    });
}
